import type { MoltbotEnv } from '../types';

/**
 * Build environment variables to pass to the OpenClaw container process
 *
 * @param env - Worker environment bindings
 * @returns Environment variables record
 */
export function buildEnvVars(env: MoltbotEnv): Record<string, string> {
  const envVars: Record<string, string> = {};

  // Cloudflare AI Gateway configuration (new native provider)
  if (env.CLOUDFLARE_AI_GATEWAY_API_KEY) {
    envVars.CLOUDFLARE_AI_GATEWAY_API_KEY = env.CLOUDFLARE_AI_GATEWAY_API_KEY;
  }
  if (env.CF_AI_GATEWAY_ACCOUNT_ID) {
    envVars.CF_AI_GATEWAY_ACCOUNT_ID = env.CF_AI_GATEWAY_ACCOUNT_ID;
  }
  if (env.CF_AI_GATEWAY_GATEWAY_ID) {
    envVars.CF_AI_GATEWAY_GATEWAY_ID = env.CF_AI_GATEWAY_GATEWAY_ID;
  }

  // Direct provider keys
  if (env.ANTHROPIC_API_KEY) envVars.ANTHROPIC_API_KEY = env.ANTHROPIC_API_KEY;
  if (env.OPENAI_API_KEY) envVars.OPENAI_API_KEY = env.OPENAI_API_KEY;

  // Legacy AI Gateway support: AI_GATEWAY_BASE_URL + AI_GATEWAY_API_KEY
  // When set, these override direct keys for backward compatibility
  if (env.AI_GATEWAY_API_KEY && env.AI_GATEWAY_BASE_URL) {
    const normalizedBaseUrl = env.AI_GATEWAY_BASE_URL.replace(/\/+$/, '');
    envVars.AI_GATEWAY_BASE_URL = normalizedBaseUrl;
    // Legacy path routes through Anthropic base URL
    envVars.ANTHROPIC_BASE_URL = normalizedBaseUrl;
    envVars.ANTHROPIC_API_KEY = env.AI_GATEWAY_API_KEY;
  } else if (env.ANTHROPIC_BASE_URL) {
    envVars.ANTHROPIC_BASE_URL = env.ANTHROPIC_BASE_URL;
  }

  // Map MOLTBOT_GATEWAY_TOKEN to OPENCLAW_GATEWAY_TOKEN (container expects this name)
  if (env.MOLTBOT_GATEWAY_TOKEN) envVars.OPENCLAW_GATEWAY_TOKEN = env.MOLTBOT_GATEWAY_TOKEN;
  if (env.DEV_MODE) envVars.OPENCLAW_DEV_MODE = env.DEV_MODE;
  if (env.TELEGRAM_BOT_TOKEN) envVars.TELEGRAM_BOT_TOKEN = env.TELEGRAM_BOT_TOKEN;
  if (env.TELEGRAM_DM_POLICY) envVars.TELEGRAM_DM_POLICY = env.TELEGRAM_DM_POLICY;
  if (env.TELEGRAM_DM_ALLOW_FROM) envVars.TELEGRAM_DM_ALLOW_FROM = env.TELEGRAM_DM_ALLOW_FROM;
  if (env.DISCORD_BOT_TOKEN) envVars.DISCORD_BOT_TOKEN = env.DISCORD_BOT_TOKEN;
  if (env.DISCORD_DM_POLICY) envVars.DISCORD_DM_POLICY = env.DISCORD_DM_POLICY;
  if (env.EMAIL_WEBHOOK_SECRET) envVars.EMAIL_WEBHOOK_SECRET = env.EMAIL_WEBHOOK_SECRET;
  if (env.EMAIL_OUTBOUND_WEBHOOK_SECRET) {
    envVars.EMAIL_OUTBOUND_WEBHOOK_SECRET = env.EMAIL_OUTBOUND_WEBHOOK_SECRET;
  }
  if (env.EMAIL_OUTBOUND_WEBHOOK_URL) envVars.EMAIL_OUTBOUND_WEBHOOK_URL = env.EMAIL_OUTBOUND_WEBHOOK_URL;
  if (env.EMAIL_FROM_ADDRESS) envVars.EMAIL_FROM_ADDRESS = env.EMAIL_FROM_ADDRESS;
  if (env.EMAIL_MAILCHANNELS_ENABLED) {
    envVars.EMAIL_MAILCHANNELS_ENABLED = env.EMAIL_MAILCHANNELS_ENABLED;
  }
  if (env.EMAIL_REQUIRE_WEBHOOK_SIGNATURE) {
    envVars.EMAIL_REQUIRE_WEBHOOK_SIGNATURE = env.EMAIL_REQUIRE_WEBHOOK_SIGNATURE;
  }
  if (env.EMAIL_DM_POLICY) envVars.EMAIL_DM_POLICY = env.EMAIL_DM_POLICY;
  if (env.EMAIL_DM_ALLOW_FROM) envVars.EMAIL_DM_ALLOW_FROM = env.EMAIL_DM_ALLOW_FROM;
  if (env.EMAIL_SUPPRESS_REPLY) envVars.EMAIL_SUPPRESS_REPLY = env.EMAIL_SUPPRESS_REPLY;
  if (env.EMAIL_SMS_ACK_ENABLED) envVars.EMAIL_SMS_ACK_ENABLED = env.EMAIL_SMS_ACK_ENABLED;
  if (env.EMAIL_SMS_ACK_TO) envVars.EMAIL_SMS_ACK_TO = env.EMAIL_SMS_ACK_TO;
  if (env.BLOOIO_API_KEY) envVars.BLOOIO_API_KEY = env.BLOOIO_API_KEY;
  if (env.BLOOIO_WEBHOOK_SECRET) envVars.BLOOIO_WEBHOOK_SECRET = env.BLOOIO_WEBHOOK_SECRET;
  if (env.BLOOIO_OUTBOUND) envVars.BLOOIO_OUTBOUND = env.BLOOIO_OUTBOUND;
  if (env.BLOOIO_DM_POLICY) envVars.BLOOIO_DM_POLICY = env.BLOOIO_DM_POLICY;
  if (env.BLOOIO_GROUP_POLICY) envVars.BLOOIO_GROUP_POLICY = env.BLOOIO_GROUP_POLICY;
  if (env.BLOOIO_DM_ALLOW_FROM) envVars.BLOOIO_DM_ALLOW_FROM = env.BLOOIO_DM_ALLOW_FROM;
  if (env.BLOOIO_GROUP_ALLOW_FROM) envVars.BLOOIO_GROUP_ALLOW_FROM = env.BLOOIO_GROUP_ALLOW_FROM;
  if (env.LINQ_API_KEY) envVars.LINQ_API_KEY = env.LINQ_API_KEY;
  if (env.LINQ_WEBHOOK_SECRET) envVars.LINQ_WEBHOOK_SECRET = env.LINQ_WEBHOOK_SECRET;
  if (env.LINQ_FROM_PHONE) envVars.LINQ_FROM_PHONE = env.LINQ_FROM_PHONE;
  if (env.LINQ_DM_ALLOW_FROM) envVars.LINQ_DM_ALLOW_FROM = env.LINQ_DM_ALLOW_FROM;
  if (env.LINQ_GROUP_ALLOW_FROM) envVars.LINQ_GROUP_ALLOW_FROM = env.LINQ_GROUP_ALLOW_FROM;
  if (env.BLUEBUBBLES_SERVER_URL) envVars.BLUEBUBBLES_SERVER_URL = env.BLUEBUBBLES_SERVER_URL;
  if (env.BLUEBUBBLES_PASSWORD) envVars.BLUEBUBBLES_PASSWORD = env.BLUEBUBBLES_PASSWORD;
  if (env.BLUEBUBBLES_WEBHOOK_PATH) envVars.BLUEBUBBLES_WEBHOOK_PATH = env.BLUEBUBBLES_WEBHOOK_PATH;
  if (env.BLUEBUBBLES_DM_POLICY) envVars.BLUEBUBBLES_DM_POLICY = env.BLUEBUBBLES_DM_POLICY;
  if (env.BLUEBUBBLES_DM_ALLOW_FROM)
    envVars.BLUEBUBBLES_DM_ALLOW_FROM = env.BLUEBUBBLES_DM_ALLOW_FROM;
  if (env.BLUEBUBBLES_GROUP_POLICY) envVars.BLUEBUBBLES_GROUP_POLICY = env.BLUEBUBBLES_GROUP_POLICY;
  if (env.BLUEBUBBLES_GROUP_ALLOW_FROM) {
    envVars.BLUEBUBBLES_GROUP_ALLOW_FROM = env.BLUEBUBBLES_GROUP_ALLOW_FROM;
  }
  if (env.BLUEBUBBLES_BLOCK_STREAMING) {
    envVars.BLUEBUBBLES_BLOCK_STREAMING = env.BLUEBUBBLES_BLOCK_STREAMING;
  }
  if (env.SLACK_BOT_TOKEN) envVars.SLACK_BOT_TOKEN = env.SLACK_BOT_TOKEN;
  if (env.SLACK_APP_TOKEN) envVars.SLACK_APP_TOKEN = env.SLACK_APP_TOKEN;
  if (env.CF_AI_GATEWAY_MODEL) envVars.CF_AI_GATEWAY_MODEL = env.CF_AI_GATEWAY_MODEL;
  if (env.CF_ACCOUNT_ID) envVars.CF_ACCOUNT_ID = env.CF_ACCOUNT_ID;
  if (env.OPENCLAW_TRUSTED_PROXIES) envVars.OPENCLAW_TRUSTED_PROXIES = env.OPENCLAW_TRUSTED_PROXIES;
  if (env.CDP_SECRET) envVars.CDP_SECRET = env.CDP_SECRET;
  if (env.WORKER_URL) envVars.WORKER_URL = env.WORKER_URL;
  if (env.GOOGLE_SECRET) envVars.GOOGLE_SECRET = env.GOOGLE_SECRET;
  if (env.GOOGLE_EMAIL) envVars.GOOGLE_EMAIL = env.GOOGLE_EMAIL;
  return envVars;
}
